# Setup
setup: multi_task

# Database
train_db_name: PASCALContext
val_db_name: PASCALContext 
trBatch: 8
valBatch: 8
nworkers: 4
ignore_index: 255

# Optimizer and scheduler
epochs: 70
optimizer: adam
optimizer_kwargs:
   lr: 0.00002
   weight_decay: 0.00001
scheduler: cosine
grad_clip_param: {'max_norm': 2, 'norm_type': 2}

# Model
model: papnet 
model_kwargs:
    diffusion:
      beta: 0.05
      num_iters: 1
backbone: swin_v2_s
backbone_kwargs:
   pretrained: True
   dilated: False
   fuse_hrnet: False
head: deeplab

# Tasks
task_dictionary:
   include_semseg: True
   include_normals: True
   include_human_parts: True
   include_sal: True
   include_edge: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_scheme: papnet
   loss_weighting: scalarization
   loss_weights:
       semseg: 1.0
       human_parts: 2.0
       sal: 5.0
       edge: 50.0
       normals: 10.0